[package]
name = "frostbyte"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40", features = ["full"] }
ethers = { version = "2.0", features = ["abigen", "ws"] }
colored = "2"
dotenv = "0.15"
anyhow = "1"
futures-util = "0.3"
